### ISSUE TITLE
dataset not available

### ISSUE THREAD

**Issue by xuhangc** [saikatdutta/Stacked_DMSHN_bokeh#10]
Hi, it seems that the download links in AIM 2020 challenge are not accessible any more. Could you share the dataset if you have any local backups?

**Comment by mySun117** [comment]
> links

Same as your situation, have you found the dataset?

**Comment by xuhangc** [comment]
> > links
> 
> Same as your situation, have you found the dataset?

No, I have also email the organizer but still no response

**Comment by xuhangc** [comment]
> > links
> 
> Same as your situation, have you found the dataset?

Hi, Dr.Peng has kindly shared the EBB dataset [here](https://github.com/JuewenPeng/BokehMe/issues/6).
