### ISSUE TITLE
Questions about runtime？

### ISSUE THREAD

**Issue by chenquan-hdu** [saikatdutta/Stacked_DMSHN_bokeh#3]
Hi,

I tried to test runtime, but I could not find detailed measurement details in the paper. I have some questions :

Q1. Is the runtime average for VAL294? Do I need to remove the running time of the first slide?

Q2. What piece of code does the runtime measure? Does it include image preprocessing? Or only calculate the time of model. predict?
        start = time.time()
        bok_pred = bokehnet(input_image)
        end = time.time() - start
        print(end)

Thank you for your help.

**Comment by saikatdutta** [comment]
Hi, 

1. Yes, it's averaged over Val294 set. Generally, removing first few slides won't matter much since we are taking average on ~300 samples.
2. Your pseudocode is correct. We use only the GPU time and exclude any I/O and preprocessing time. Don't forget to use `torch.no_grad()`.

**Comment by chenquan-hdu** [comment]
Hi,

I tested the DMSHN average runtime, which was about 0.017s.  Very fast !

Thank you.
