### ISSUE TITLE
One quick question。

### ISSUE THREAD

**Issue by chenquan-hdu** [saikatdutta/Stacked_DMSHN_bokeh#5]
Hi，

First, thank you for your sharing and help.
I studied DMSHN and found you compared it to PyNET. I tried to repeat PyNET(tensorflow) but failed (others had the same problem as me, color distortion in level 1) and I contacted the author but no one responded. I hope you can share your experience in repeating PyNET.
[https://github.com/aiff22/PyNET-Bokeh](url)

Hope you can help me. Thanks again.

**Comment by saikatdutta** [comment]
Hi, are you having trouble while evaluating using PyNET pretrained model?

**Comment by chenquan-hdu** [comment]
Hi,
I'm having trouble retraining PyNET (color distortion at level1). I'm using the 'train.py' provided by the author and following the training steps provided by him, but there are problems. Someone else has the same problem but doesn't know how to solve it.

**Comment by saikatdutta** [comment]
I hadn't tried training PyNet from scratch, I am not sure how to solve this problem.

**Comment by chenquan-hdu** [comment]
For PyNET in Table 1, did you use the pre-training model provided by the author to measure indicators, PSNR,SSIM,LPIPS?

**Comment by Soester10** [comment]
Yes, I have the same question. For PyNET, the pretrained model was trained on the entire dataset, and tested on the test data (not available for public). But in the DMSHN paper, both models are compared by testing on the Val294 dataset (last 294 images from training data), and the DMSHN model being trained only on part of the training dataset (excluding Val294). Shouldn't there be a bias as the PyNET model is tested on seen dataset while the DMSHN model is tested on unseen dataset?

**Comment by saikatdutta** [comment]
@chenquan-hdu Yes, I used the pre-trained model for PyNET provided by authors.
@Soester10 Yes, there can be bias. For fair comparison, all the models should be trained on the same training data. Due to time and resource constraints, we couldn't do that.

**Comment by chenquan-hdu** [comment]
Thank you again.

**Comment by 13sunmin** [comment]
> 嗨， 我在重新训练 PyNET 时遇到了麻烦（级别 1 的颜色失真）。我正在使用作者提供的“train.py”并按照他提供的培训步骤进行操作，但是存在问题。其他人也有同样的问题，但不知道如何解决。

Do you have an EBB dataset?
