### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 13sunmin** [saikatdutta/Stacked_DMSHN_bokeh#6]
How to obtain the ebb dataset? There is no download portal for the website link.
After I registered, I didn't see a place to download.

**Comment by saikatdutta** [comment]
Please check this page: https://competitions.codalab.org/competitions/24716#participate

**Comment by 13sunmin** [comment]
> 请查看此页面：[https](https://competitions.codalab.org/competitions/24716#participate) : [//competitions.codalab.org/competitions/24716#participate](https://competitions.codalab.org/competitions/24716#participate)


Thank you very much. I solved it
